import { Request, Response } from "express";
import { UserModel, UserType } from "./user.model";

// Action to create a new user
export function createUser(req: Request, res: Response) {
    const { name, email, password, role = 'user' } = req.body as Omit<UserType, '_id'>;

    // Create a new User instance, no need to pass _id as it will be auto-generated by MongoDB
    const newUser = new UserModel({
        name,
        email,
        password,
        role,
        active: true
    });

    // Save the user to MongoDB
    newUser.save()
        .then((user) => res.status(201).json({ message: "User created", user }))
        .catch(err => res.status(500).json({ message: "Error creating user", error: err.message }));
}
